version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_CMD=uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    command: sh -c "$UVICORN_CMD"
    env_file:
      - ./backend/.env

  ui:
    build: ./ui
    ports:
      - "3039:3039"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start"
    env_file:
      - ./ui/.env


volumes:
  backend-data:
  ui-data:
